<?php
/**
 * European language URL codes mapped to locale identifiers.
 */
return [
    'App' => [
        'defaultLanguage' => 'hu',
        'languages' => [
            'bg' => 'bg_BG',
            'bs' => 'bs_BA',
            'ca' => 'ca_ES',
            'cs' => 'cs_CZ',
            'cy' => 'cy_GB',
            'da' => 'da_DK',
            'de' => 'de_DE',
            'el' => 'el_GR',
            'en' => 'en_GB',
            'es' => 'es_ES',
            'et' => 'et_EE',
            'eu' => 'eu_ES',
            'fi' => 'fi_FI',
            'fr' => 'fr_FR',
            'ga' => 'ga_IE',
            'gl' => 'gl_ES',
            'hr' => 'hr_HR',
            'hu' => 'hu_HU',
            'is' => 'is_IS',
            'it' => 'it_IT',
            'lb' => 'lb_LU',
            'lt' => 'lt_LT',
            'lv' => 'lv_LV',
            'mk' => 'mk_MK',
            'mt' => 'mt_MT',
            'nl' => 'nl_NL',
            'no' => 'nb_NO',
            'pl' => 'pl_PL',
            'pt' => 'pt_PT',
            'ro' => 'ro_RO',
            'ru' => 'ru_RU',
            'sk' => 'sk_SK',
            'sl' => 'sl_SI',
            'sq' => 'sq_AL',
            'sr' => 'sr_RS',
            'sv' => 'sv_SE',
            'tr' => 'tr_TR',
            'uk' => 'uk_UA',
        ],
    ],
];
